Repository jenkinsci/jsoup-plugin, pull requests merged in 2025-02, with the labels that each got.

#4 Require 2.346.3
  pom.xml
Labels: dependencies

#5 chore(github): Add CODEOWNERS
  .github/CODEOWNERS
Labels: chore

#6 chore(dependencies): Automate dependency updates with Dependabot
  .github/dependabot.yml
Labels: chore

#7 Enable incrementals
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
Labels: chore

#10 Use Jenkinsfile from archetype
  Jenkinsfile
Labels: chore

#11 chore(pom): Use recommended core version 2.462.3, and Java 11.
  pom.xml
Labels: developer

#12 Prepare for CD
  .mvn/maven.config
  README.md
  pom.xml
  src/main/resources/index.jelly
Labels: enhancement

#13 Add CD workflows
  .github/workflows/cd.yaml
Labels: skip-changelog

#14 Update readme
  LICENSE.md
  README.md
Labels: documentation

#15 Enable Jenkins Security Scan
  .github/workflows/jenkins-security-scan.yml
Labels: chore
